### ISSUE TITLE
Guzzle 6 Broken?

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/guzzle#1079]
Just upgrading some pretty simple code to guzzle 6 from 5 to find it broken.

```
[2015-05-26 22:49:38] production.ERROR: exception 'InvalidArgumentException' with message 'Invalid resource type: array' in /web/app1/vendor/guzzlehttp/psr7/src/functions.php:113
Stack trace:
#0 /web/app1/vendor/guzzlehttp/psr7/src/Request.php(62): GuzzleHttp\Psr7\stream_for(Array)
#1 /web/app1/vendor/guzzlehttp/guzzle/src/Client.php(117): GuzzleHttp\Psr7\Request->__construct('post', Object(GuzzleHttp\Psr7\Uri), Array, Array, '1.1')
#2 /web/app1/vendor/guzzlehttp/guzzle/src/Client.php(127): GuzzleHttp\Client->requestAsync('post', 'https://github....', Array)
#3 /web/app1/vendor/guzzlehttp/guzzle/src/Client.php(88): GuzzleHttp\Client->request('post', 'https://github....', Array)
#4 /web/app1/vendor/styleci/login/src/LoginProvider.php(158): GuzzleHttp\Client->__call('post', Array)
#5 /web/app1/vendor/styleci/login/src/LoginProvider.php(158): GuzzleHttp\Client->post('https://github....', Array)
```

The code in question is pretty simple: https://github.com/StyleCI/Login/blob/v0.1.1-alpha/src/LoginProvider.php#L155.

**Comment by GrahamCampbell** [comment]
Just upgrading some pretty simple code to guzzle 6 from 5 to find it broken.

```
[2015-05-26 22:49:38] production.ERROR: exception 'InvalidArgumentException' with message 'Invalid resource type: array' in /web/app1/vendor/guzzlehttp/psr7/src/functions.php:113
Stack trace:
#0 /web/app1/vendor/guzzlehttp/psr7/src/Request.php(62): GuzzleHttp\Psr7\stream_for(Array)
#1 /web/app1/vendor/guzzlehttp/guzzle/src/Client.php(117): GuzzleHttp\Psr7\Request->__construct('post', Object(GuzzleHttp\Psr7\Uri), Array, Array, '1.1')
#2 /web/app1/vendor/guzzlehttp/guzzle/src/Client.php(127): GuzzleHttp\Client->requestAsync('post', 'https://github....', Array)
#3 /web/app1/vendor/guzzlehttp/guzzle/src/Client.php(88): GuzzleHttp\Client->request('post', 'https://github....', Array)
#4 /web/app1/vendor/styleci/login/src/LoginProvider.php(158): GuzzleHttp\Client->__call('post', Array)
#5 /web/app1/vendor/styleci/login/src/LoginProvider.php(158): GuzzleHttp\Client->post('https://github....', Array)
```

The code in question is pretty simple: https://github.com/StyleCI/Login/blob/v0.1.1-alpha/src/LoginProvider.php#L155.

**Comment by GrahamCampbell** [comment]
Is it not supported for `body` to be an array anymore. Do I need to encode it to a string first in guzzle 6?

**Comment by GrahamCampbell** [comment]
Just wanting to be clear if this is intended, or is a bug. :)

**Comment by mtdowling** [comment]
Yeah this is intended. `body` cannot be an array. You need to pass in `form_params` or `multipart` options. More info at https://github.com/guzzle/guzzle/blob/master/src/RequestOptions.php

**Comment by GrahamCampbell** [comment]
Ok, thanks.

**Comment by taylorotwell** [comment]
:(
