### ISSUE TITLE
Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 404'

### ISSUE THREAD

**Issue by iyourplus** [guzzle/guzzle#1206]
It's php code to use guzzle, but it can not work.

```php
<?php

require 'vendor/autoload.php';

use GuzzleHttp\Client;

$client = new GuzzleHttp\Client(['base_uri' => 'http://localhost:8000/api/v1/']);
$response = $client->get('users');
var_dump($response);
```

It looks like so incomprehensible, because I can telnet localhost port 8000. And I can get response infomation with browser which url is http://localhost:8000/api/v1/users.
So, why it shows the following message.

```
'cURL error 7: Failed to connect to localhost port 8000: Connection refused
```

The entire exception message:
```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to localhost port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:168
Stack trace:
#0 /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(132): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(98): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\Easy in /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 168

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to localhost port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:168
Stack trace:
#0 /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(132): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(98): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\Easy in /Users/iyourplus/demo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 168
```

**Comment by kamilsk** [comment]
Hi!
> 'Client error: 404'

and

> cURL error 7: Failed to connect to localhost port 8000: Connection refused

How does it correlate?

> cURL error 7

This problem is at a lower level, and is not connected with the Guzzle. Run `curl http://localhost:8000/api/v1/users` in terminal and what will be returned?

**Comment by iyourplus** [comment]
Run curl http://localhost:8000/api/v1/users in terminal and it return connection refused message. But run curl --ipv4 http://localhost:8000/api/v1/users in terminal and it work fine.

**Comment by kamilsk** [comment]
use 127.0.0.1 instead of localhost

**Comment by iyourplus** [comment]
it works fine. thanks!
