### ISSUE TITLE
Uncaught exception 'GuzzleHttp\Exception\ClientException' on setUserAgent call

### ISSUE THREAD

**Issue by chipitsine** [guzzle/guzzle#1267]
```
{
   "require": {
      "guzzlehttp/guzzle": "~6.1"
   }
}
```

php script:

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$client = new \GuzzleHttp\Client([
        'base_uri' => 'https://malwr.com',
        'timeout'  => 30.0,
        'cookies' => true,
]);

$client->setUserAgent('Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0');

$request = $client->get('/account/login/', ['debug' => true]);

?>
```

it unexpectedly dies on 'setUserAgent' call:

```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 404' in /xxx/vendor/guzzlehttp/guzzle/src/Middleware.php:69
Stack trace:
#0 /xxx/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 /xxx/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#2 /xxx/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#3 /xxx/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#4 /xxx/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 /xxx/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 /xxx/vendor/guzzlehttp/promises/src/Promise.php(21 in /root/kaspersky/vendor/guzzlehttp/guzzle/src/Middleware.php on line 69
```

I beleive setUserAgent should not perform http requests at all, so it shouldn't throw 404, right ?

**Comment by chipitsine** [comment]
up

**Comment by jeskew** [comment]
Guzzle v6 has no `setUserAgent` method, so that call is falling back to `__call`, which tries to perform an HTTP request.

For PSR-7 compatibility, you should construct the client with a default user agent header:
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$client = new \GuzzleHttp\Client([
    'base_uri' => 'https://malwr.com',
    'timeout'  => 30.0,
    'cookies' => true,
    'headers' => [
        'User-Agent' => 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
    ],    
]);

$request = $client->get('/account/login/', ['debug' => true]);
```

**Comment by chipitsine** [comment]
unexpected exception '404' is not what people usually expect on setUserAgent().
maybe it should throw more resonable exception ?

**Comment by jeskew** [comment]
Guzzle allows you to send a message with any HTTP verb via its [`__call`](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L76) method. This magic method is what exposes the `get`, `post`, and `delete` methods, as well as methods for less common verbs like `report` and `propfind`. In theory, you could configure your server to respond to the verb "setuseragent" (or any other valid string), so it's not a string that should break the standard behavior of calling undefined methods on a Guzzle client.
