### ISSUE TITLE
Port 43

### ISSUE THREAD

**Issue by gumelar** [guzzle/guzzle#1428]
I have this cURL code which is actually works.

```
$ch = curl_init('whois.nic.co');

curl_setopt($ch, CURLOPT_PORT, 43);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 30);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "example.co\r\n");

$response = curl_exec($ch);
curl_close($ch);
```

I want to use Guzzle rather than cURL but seems like it doesn't work using port 43

```
$client = new Client(['base_uri' => 'whois.nic.co:43']);
$response = $client->post('', ['Content-Type' => 'text/plain; charset=UTF8'], "example.co\r\n");
```

The code above return `cURL error 0: The cURL request was retried 3 times and did not succeed. ...`

**Comment by mtdowling** [comment]
I think guzzle requires a scheme in the URI. Try adding http or https to your url.

**Comment by gumelar** [comment]
Guzzle will prepend `HTTP://` if url doesn't have a protocol so adding protocol doesn't help.

**Comment by mtdowling** [comment]
What are the contents from using debug output? http://docs.guzzlephp.org/en/latest/request-options.html#debug

**Comment by gumelar** [comment]
Here is the output:

```
* Rebuilt URL to: whois.nic.co:43/
* Hostname whois.nic.co was found in DNS cache
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#0)
> POST / HTTP/1.1
Host: whois.nic.co:43
User-Agent: GuzzleHttp/6.1.1 curl/7.46.0 PHP/5.6.17
Content-Length: 12

* upload completely sent off: 12 out of 12 bytes
* Connection #0 to host whois.nic.co left intact
* Rebuilt URL to: whois.nic.co:43/
* Connection 0 seems to be dead!
* Closing connection 0
* Hostname whois.nic.co was found in DNS cache
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#1)
> POST / HTTP/1.1
Host: whois.nic.co:43
User-Agent: GuzzleHttp/6.1.1 curl/7.46.0 PHP/5.6.17
Content-Length: 12

* upload completely sent off: 12 out of 12 bytes
* Connection #1 to host whois.nic.co left intact
* Rebuilt URL to: whois.nic.co:43/
* Connection 1 seems to be dead!
* Closing connection 1
* Hostname whois.nic.co was found in DNS cache
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#2)
> POST / HTTP/1.1
Host: whois.nic.co:43
User-Agent: GuzzleHttp/6.1.1 curl/7.46.0 PHP/5.6.17
Content-Length: 12

* upload completely sent off: 12 out of 12 bytes
* Connection #2 to host whois.nic.co left intact
```

**Comment by gumelar** [comment]
On my code `curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "example.co\r\n");` any idea how to create set `CURLOPT_CUSTOMREQUEST` on guzzle?

Trying with `$client->request("example.co\r\n", 'whois.nic.co:43', ['debug' => true]);` but return the same error.

**Comment by mtdowling** [comment]
That's a really strange way to try and send an HTTP request. Why are you setting the HTTP method to "example.co\r\n"? Are you trying to send a GET request through a proxy? Can you provide the CURLOPT_VERBOSE output of your working curl example?

**Comment by gumelar** [comment]
Yes I think so but it's working for any whois server not just whois.nic.co so I think this how it works. Here is the header output using cURL:

```
* Rebuilt URL to: whois.nic.co/
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#0)
> example.co

 / HTTP/1.1
Host: whois.nic.co:43
Accept: */*

* Connection #0 to host whois.nic.co left intact
```
And body output:

```
Domain Name:                                 EXAMPLE.CO
Domain ID:                                   D734260-CO
Sponsoring Registrar:                        RESTRICTED AND RESERVED NAMES .COINTERNET
Sponsoring Registrar IANA ID:                672943168
Registrar URL (registration services):       www.cointernet.com.co
Domain Status:                               serverTransferProhibited
Variant:                                     EXAMPLE.CO
....
```

**Comment by shaunbramley** [comment]
```
$stack = new GuzzleHttp\HandlerStack(new GuzzleHttp\Handler\StreamHandler());

$logger = new Monolog\Logger('test');
$logger->pushHandler(new Monolog\Handler\StreamHandler('php://stdout'));

$formatter = new GuzzleHttp\MessageFormatter('{request} {response}');

//$stack->push(GuzzleHttp\Middleware::log($logger, $formatter));


$uri = 'http://whois.my.ga:43';

$headers = [
    'Content-Type' => 'text/plain; charset=UTF8',
    'Accept' => '*/*'
];

$body = 'example.ga';
    
$client = new GuzzleHttp\Client([
    'debug' => true,
    'handler' => $stack,
]);

$response = $client->request($body, $uri, [
    'body' => $body,
    'headers' => $headers,
]);

print_r($response->getBody()->getContents());
```

will result in
```
<EXAMPLE.GA http://whois.my.ga:43> [CONNECT]
<EXAMPLE.GA http://whois.my.ga:43> [FAILURE] severity: "2" message: "
"
<EXAMPLE.GA http://whois.my.ga:43> [PROGRESS]
PHP Notice:  Undefined offset: 1 in C:\Users\Shaun Bramley\Zend\workspaces\DefaultWorkspace12.5\StackOverflow Answers\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php on line 102
PHP Notice:  Undefined offset: 1 in C:\Users\Shaun Bramley\Zend\workspaces\DefaultWorkspace12.5\StackOverflow Answers\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php on line 103
   Owner contact:
      Organization: N/A
      Name:         Mr Maurice van der Meer
      Address:      Keizersgracht 213
      Zipcode:      1016DT
      City:         Amsterdam
      State:        Noord-Holland
      Country:      Netherlands
      Phone:        +31-20-5315725
      Fax:          +31--
      E-mail:       example@renamethe.net

   Admin contact:
      Organization: N/A
      Name:         Mr Maurice van der Meer
      Address:      Keizersgracht 213
      Zipcode:      1016DT
      City:         Amsterdam
      State:        Noord-Holland
      Country:      Netherlands
      Phone:        +31-20-5315725
      Fax:          +31--
      E-mail:       example@renamethe.net

   Billing contact:
      Organization: N/A
      Name:         Mr Maurice van der Meer
      Address:      Keizersgracht 213
      Zipcode:      1016DT
      City:         Amsterdam
      State:        Noord-Holland
      Country:      Netherlands
      Phone:        +31-20-5315725
      Fax:          +31--
      E-mail:       example@renamethe.net

   Tech contact:
      Organization: N/A
      Name:         Mr Maurice van der Meer
      Address:      Keizersgracht 213
      Zipcode:      1016DT
      City:         Amsterdam
      State:        Noord-Holland
      Country:      Netherlands
      Phone:        +31-20-5315725
      Fax:          +31
```

The two "Undefined Index" are being thrown within StreamHandler::createResponse().  The whois protocol, being significantly simpler than traditional http requests does not contain all of the "parts" that are used to properly populate the header information for the response object.

For reference my system: Windows 10, PHP 7.0.0, Guzzle 6.1.1, GuzzleHttp\Promises 1.1.0, GuzzleHttp\Psr7 1.2.3

**Comment by shaunbramley** [comment]
The same example functions identically on mac os, PHP7.0.4, Guzzle 6.1.1, GuzzleHttp\Promises 1.1.0, GuzzleHttp\Psr7 1.2.3.

**Comment by shaunbramley** [comment]
```
$stack = GuzzleHttp\HandlerStack::create();

$uri = 'http://whois.nic.co:43';

$headers = [
    'Content-Type' => 'text/plain; charset=UTF8',
    'Accept' => '*/*',
];

$body = "example.co";

$client = new GuzzleHttp\Client([
    'debug' => true,
    'handler' => $stack,
]);

$response = $client->request($body, $uri, [
    'headers' => $headers,
    'body' => $body,
]);

print_r($response->getBody()->getContents());
```

Will die with the following output

```
Shauns-MacBook-Air:stackoverflow shaunbramley$ php index.php
* Rebuilt URL to: http://whois.nic.co:43/
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#0)
> EXAMPLE.CO / HTTP/1.1
Host: whois.nic.co:43
User-Agent: GuzzleHttp/6.1.1 curl/7.43.0 PHP/7.0.4
Content-Type: text/plain; charset=UTF8
Accept: */*
Content-Length: 10

* upload completely sent off: 10 out of 10 bytes
* Connection #0 to host whois.nic.co left intact
* Rebuilt URL to: http://whois.nic.co:43/
* Found bundle for host whois.nic.co: 0x7fe4b2f01640
* Connection 0 seems to be dead!
* Closing connection 0
* Hostname whois.nic.co was found in DNS cache
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#1)
> EXAMPLE.CO / HTTP/1.1
Host: whois.nic.co:43
User-Agent: GuzzleHttp/6.1.1 curl/7.43.0 PHP/7.0.4
Content-Type: text/plain; charset=UTF8
Accept: */*
Content-Length: 10

* upload completely sent off: 10 out of 10 bytes
* Connection #1 to host whois.nic.co left intact
* Rebuilt URL to: http://whois.nic.co:43/
* Found bundle for host whois.nic.co: 0x7fe4b2f01300
* Connection 1 seems to be dead!
* Closing connection 1
* Hostname whois.nic.co was found in DNS cache
*   Trying 156.154.25.94...
* Connected to whois.nic.co (156.154.25.94) port 43 (#2)
> EXAMPLE.CO / HTTP/1.1
Host: whois.nic.co:43
User-Agent: GuzzleHttp/6.1.1 curl/7.43.0 PHP/7.0.4
Content-Type: text/plain; charset=UTF8
Accept: */*
Content-Length: 10

* upload completely sent off: 10 out of 10 bytes
* Connection #2 to host whois.nic.co left intact
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(485): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(147): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Objec in /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(485): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(147): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Objec in /Users/shaunbramley/Zend/workspaces/DefaultWorkspace/stackoverflow/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187
Shauns-MacBook-Air:stackoverflow shaunbramley$ 
```

**Comment by mtdowling** [comment]
I played around with this for a bit, and I can't figure it out... I don't really understand what you're trying to do here, and this seems like a special case to the point that it isn't not supported in Guzzle.

**Comment by shaunbramley** [comment]
@mtdowling I was simply showing that it is *possible* using the StreamHandler; however, it is most definitely a hack.  Viewing internals of both StreamHandler and CurlHandler, it is evident that  the whois protocol is not an intended use case.  It took a few tries after viewing the output of `curl -v -X "example.ga" whois.my.ga:43`.

**Comment by mtdowling** [comment]
Thanks for following up with that. I'll go ahead and resolve this since it isn't supported.

**Comment by pentagonal** [comment]
Same with me ..
This try to create socket connection stream (on this case has use telnet direct via curl)

Below image is the handler get version of return header.
```php
// on line 102 GuzzleHttp\Handler\StreamHandler
$ver = explode('/', $parts[0])[1];
```

![image](https://user-images.githubusercontent.com/17354203/28915340-05343828-7869-11e7-9e81-9648998c9d95.png)

On this case on telnet does not returning **header version** (such as : whois.iana.org), telnet response only returning body.

Result has been attached

![image](https://user-images.githubusercontent.com/17354203/28915563-b88e8ab8-7869-11e7-9e0a-4f82c21a9ff2.png)
