### ISSUE TITLE
Error 'cURL error 52: Empty reply from server.' when sending large file.

### ISSUE THREAD

**Issue by pmxjason** [guzzle/guzzle#1848]
Hello,

I was hoping someone could shed some light on an error which I am receiving. This is my code:

    $client = new \GuzzleHttp\Client();
    $response = $client->post(
        $url,
        [
            'exceptions' => FALSE,
            'multipart' => [
                [
                    'name'     => 'filename',
                    'contents' => $import->format(new CsvFormatter()),
                    'filename'  => "import_{$request->getPMXID()}.csv"
                ]
            ]
        ]
    );

It is being used frequently and works fine. I recently started developing a new feature which would lead to larger files. This is when the cURL error started happening. If the file is a few hundred KB it works fine. It the file is 1.8MB it doesn't. I don't know where the cut off is.

Googling has not helped. I dug into the CurlFactory class to try to shed some light on what the curl request looked like. I noticed there is a difference between sending based on content size. For a small amount of content the request contains:

> --16b49cbca986ad7a8d042d673018bb96be0e2b31
> Content-Disposition: form-data; name="filename"; filename="import_200003626_32.csv"
> Content-Length: 5
> Content-Type: text/csv
> 
> asddd
> --16b49cbca986ad7a8d042d673018bb96be0e2b31--

For a large request a MultipartStream object is created. For a small request the Except header is empty. For a large request the Except header is 100-Continue.

I tried the following:

1) Saved the file to disk, instead of passing in a string I passed in a file handle. Same Error.
2) I tried sending the same request using postman to my api. Works.
3) I tried doing a curl request from my server using the large file. Works fine.
4) I set expect to false for the large file. Same Error.
5) I tried setting stream to false for the large file. Same error.

I feel that this could be a bug in my api being unable to handle the request in the way Guzzle is sending it. As I said previously, the server handles a standard curl request with the same file content fine. Does guzzle handle a 5 character string and 5MB string differently? How does this influence the curl request?

I am using Guzzle 6.2

**Comment by tomzx** [comment]
Hello,

Has this issue been resolved or do you still require assistance with it?

**Comment by manju16832003** [comment]
Same here. 
Is there any updates on this issue.

![screen shot 2018-01-14 at 23 06 53](https://user-images.githubusercontent.com/5035624/34917300-a6371050-f97f-11e7-9f9e-d80c9a28a9ec.png)

**Comment by manju16832003** [comment]
Here is the full stack trace
```
[2018-01-14 15:09:52] local.ERROR: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186)
[stacktrace]
#0 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)
#1 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#2 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#3 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 /var/www/senangkira-dashboard-v1/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Client->requestAsync('GET', Object(GuzzleHttp\\Psr7\\Uri), Array)
#13 /var/www/senangkira-dashboard-v1/app/Http/Controllers/DashboardController.php(37): GuzzleHttp\\Client->request('GET', 'http://128.199....')
#14 [internal function]: App\\Http\\Controllers\\DashboardController->index(Object(Illuminate\\Http\\Request))
#15 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#17 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\DashboardController), 'index')
#18 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#19 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#20 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#39 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#40 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#41 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#42 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/senangkira-dashboard-v1/app/Http/Middleware/LoadUser.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LoadUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/senangkira-dashboard-v1/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#66 /var/www/senangkira-dashboard-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#67 /var/www/senangkira-dashboard-v1/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#68 {main}
"}

```

**Comment by MichaelBelgium** [comment]
I'm having the same error with API calls (in Laravel)

```PHP
$response = $this->client->request('PUT', route('api.category.update', ['category' => $category]), [
            'form_params' => $request->all()
        ])->getBody();
```

It occurs randomly.

Full stack:

```
[2018-05-30 17:52:55] staging.ERROR: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
[stacktrace]
#0 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)
#1 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#2 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#3 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 /var/www/html/bakkerij/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Client->requestAsync('PUT', Object(GuzzleHttp\\Psr7\\Uri), Array)
#13 /var/www/html/bakkerij/app/Http/Controllers/CMS/CategoryController.php(84): GuzzleHttp\\Client->request('PUT', 'http://dev.bakk...', Array)
#14 [internal function]: App\\Http\\Controllers\\CMS\\CategoryController->update(Object(Illuminate\\Http\\Request), Object(App\\Models\\Category))
#15 /var/www/html/bakkerij/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /var/www/html/bakkerij/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#17 /var/www/html/bakkerij/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CMS\\CategoryController), 'update')
#18 /var/www/html/bakkerij/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#19 /var/www/html/bakkerij/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
....
```

**Comment by Kerren-Entrostat** [comment]
@MichaelBelgium how?

**Comment by MichaelBelgium** [comment]
@Kerren-Entrostat it only happened on my PUT requests and then i realized its not an issue from guzzle. 

I had an infinite loop in my model observer which took ofcourse ages and it returned that guzzle exception cuz no response

**Comment by igancev** [comment]
I'm having the same error when sending a file larger than 1MB. Using version 6.3.2.
My code:

```php
$client = new \GuzzleHttp\Client();
$options = [
    'multipart' => [
        [
            'name'     => 'files[]',
            'contents' => fopen('/path/to/file/larger/1MB.ext', 'r'), // or many files, the size of which together exceeds 1MB
        ],
    ]
];
$response = $client->request('POST', 'http://url.local', $options);
```

Full stack:

```
[GuzzleHttp\Exception\ConnectException] 
cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (0)
/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
#0: GuzzleHttp\Handler\CurlFactory::createRejection(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:149
#1: GuzzleHttp\Handler\CurlFactory::finishError(object, object, object)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:102
#2: GuzzleHttp\Handler\CurlFactory::finish(object, object, object)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php:43
#3: GuzzleHttp\Handler\CurlHandler->__invoke(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:28
#4: GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:51
#5: GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php:66
#6: GuzzleHttp\PrepareBodyMiddleware->__invoke(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Middleware.php:30
#7: GuzzleHttp\Middleware::GuzzleHttp\{closure}(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php:70
#8: GuzzleHttp\RedirectMiddleware->__invoke(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Middleware.php:60
#9: GuzzleHttp\Middleware::GuzzleHttp\{closure}(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/HandlerStack.php:67
#10: GuzzleHttp\HandlerStack->__invoke(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Client.php:277
#11: GuzzleHttp\Client->transfer(object, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Client.php:125
#12: GuzzleHttp\Client->requestAsync(string, string, array)
	/var/www/bitrix/local/vendor/guzzlehttp/guzzle/src/Client.php:131
#13: GuzzleHttp\Client->request(string, string, array)
	/var/www/bitrix/test.php:40
```

Reason for that line 253 of class GuzzleHttp\Handler\CurlFactory, method CurlFactory::applyBody() https://github.com/guzzle/guzzle/blob/6.3.2/src/Handler/CurlFactory.php#L253



Temporarily solved the problem by adding header *'Content-Length:1'* by the request:

```php
$client = new \GuzzleHttp\Client();
$options = [
    // this header value is deceives this condition https://github.com/guzzle/guzzle/blob/6.3.2/src/Handler/CurlFactory.php#L253
    'headers' => [
        'Content-Length' => 1
    ],
    'multipart' => [
        [
            'name'     => 'files[]',
            'contents' => fopen('/path/to/file/larger/1MB.ext', 'r'), // or many files, the size of which together exceeds 1MB
        ],
    ]
];
$response = $client->request('POST', 'http://url.local', $options);

```

But I don't think it's the right thing to do. Does anyone know why this behavior occurs?


**P.S.** Naked curl works well:


```php
$pathToBigFile = '/path/to/file/larger/1MB.ext';

$postdata = array(
    'file' => new \CURLFile($pathToBigFile, null, basename($pathToBigFile)),
);

if( $curl = curl_init() ) {
    curl_setopt($curl, CURLOPT_URL, 'http://url.local');
    curl_setopt($curl, CURLOPT_RETURNTRANSFER,true);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $postdata);
    curl_setopt($curl,CURLOPT_ENCODING, '');
    $out = curl_exec($curl);
    curl_close($curl);
}
```

**Comment by HtetwaiyanAung1996** [comment]
Please Help Me

**Comment by HtetwaiyanAung1996** [comment]
fuck oofff

**Comment by dharbinjaep** [comment]
Did anyone ever find a solution for this? I'm having the same thing happening.

**Comment by Jones-S** [comment]
I have the same error, but it can't be related to file-size. I suspect that because I send 4 requests right when loading a page to my proxy, where I have guzzle forwarding my request, it somehow crashes... Could that be?

**Comment by janholusa** [comment]
Hello, I have the same issue. Does anyone find out what was causing this problem? Is it guzzle, or opposite side does not reply correctly when big file is send??

**Comment by amit-viacon** [comment]
I am getting same error

**Comment by dharbinjaep** [comment]
Hey all,

After a lot of debugging, our problem was the TCP_KEEPALIVE check. it's a curl option: https://curl.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

We set it as:
`
        ...
        $guzzleRequest['curl'] = [
            CURLOPT_TCP_KEEPALIVE => 1,
        ];
        ...
        $response = $guzzleClient->request(
              $method,
              $path,
              $guzzleRequest
         );
         ...
`

I hope this helps some of you. Cheers!

**Comment by amit-viacon** [comment]
> Hey all,
> 
> After a lot of debugging, our problem was the TCP_KEEPALIVE check. it's a curl option: https://curl.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html
> 
> We set it as:
> 
> ```
>       ...
>       $guzzleRequest['curl'] = [
>           CURLOPT_TCP_KEEPALIVE => 1,
>       ];
>       ...
>       $response = $guzzleClient->request(
>           $method,
>           $path,
>           $guzzleRequest
>       );
>       ...
> ```
> 
> I hope this helps some of you. Cheers!


### Using Http facade:

```php
Http::withOptions([
     'curl' => [CURLOPT_TCP_KEEPALIVE => 1]
])->get($url);
```

**Comment by Tom-Ravn** [comment]
In my case webserver did not accept default user-agent string so I had to fake one in Guzzle library.
```
        $client = new Client();
        $options = [
            'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36', // Example User-Agent string from Google Chrome
            ],
        ];
        $response = $client->get($this->url, $options);
        $textContent = $response->getBody()->getContents();
```
