### ISSUE TITLE
Fatal error on simple 404

### ISSUE THREAD

**Issue by ghola** [guzzle/guzzle#1947]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

Requesting a simple url which does not exist (browser returns 404), results in the following fatal error:
```
PHP Notice:  Undefined variable: request in /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/BadResponseException.php on line 25
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to GuzzleHttp\Exception\RequestException::__construct() must implement interface Psr\Http\Message\RequestInterface, null given, called in /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/BadResponseException.php on line 25 and defined in /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:23
Stack trace:
#0 /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/BadResponseException.php(25): GuzzleHttp\Exception\RequestException->__construct('Client error: `...', NULL, Object(GuzzleHttp\Psr7\Response), NULL, Array)
#1 /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php(113): GuzzleHttp\Exception\BadResponseException->__construct('Client error: `...', Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array)
#2 /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(Guz in /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 23
```

It happens even if I do not set `http_errors` to true.

#### Expected Behavior

I expect a plain `GuzzleHttp\Exception\ClientException`, since it's a 404.

#### Steps to Reproduce

Just execute this plain script:
```php
<?php

require 'vendor/autoload.php';

$client = new \GuzzleHttp\Client(['base_uri' => 'http://google.com/boom']);

$response = $client->get('', ['http_errors' => true]);
```

**Comment by ghola** [comment]
The issue is not present in 6.2.3 so it was introduced in 6.3.0. This is the output of the test code on 6.2.3:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET http://google.com/boom` resulted in a `404 Not Found` response:
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, w (truncated...)
 in /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/provisioner.race.box/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/provisioner.race.box/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/provisioner.race.box/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Prom in /var/www/provisioner.race.box/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111
```

**Comment by bjoernffm** [comment]
Hi, I just tried to reproduce the bug with version 6.3.0. Since I was unable to reproduce, I checked if this issue got already been solved.

I think it is: https://github.com/guzzle/guzzle/pull/1642

@ghola could you do an update and check again?

**Comment by sagikazarmark** [comment]
Looks like some nasty 7.x regression, although based on code analysis and the stack trace I have no idea what could have gone wrong. The first exception obviously receives the parameter, then somehow it is not passed to the parent constructor....but it is.

#1642 is about the response parameter, the error message complains about the missing request, so I'm not sure it's related.

**Comment by sagikazarmark** [comment]
Just tried running this code on 7.2 and 5.6: on both I received:

```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET http://google.com/boom` resulted in a `404 Not Found` response:
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, w (truncated...)
 in /app/src/Exception/RequestException.php:113
Stack trace:
#0 /app/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /app/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /app/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /app/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /app/vendor/guzzlehttp/promises/src/Promise.php(223): Guzzl in /app/src/Exception/RequestException.php on line 113
```

**Comment by ghola** [comment]
I cannot reproduce this anymore with version 6.3.0. I just tested on PHP 5.5, 7.1 and 7.2. I'm not sure how this is possible as I toyed quite a bit with the initial testing before posting the bug report. Anyway, closing.

Thank you for the feedback.

**Comment by steedadev** [comment]
I'm having the same issue using  with version 6.3.

(1/1) ClientExceptionClient error: `GET https://apirest.3dcart.com/3dCartWebAPI/v1/Products/15627` resulted in a `404 Not Found` response
--
in RequestException.php line 113
at RequestException::create(object(Request), object(Response))in Middleware.php line 66
at Middleware::GuzzleHttp\{closure}(object(Response))in Promise.php line 203
at Promise::callHandler(1, object(Response), array(object(Promise), object(Closure), null))in Promise.php line 156
at Promise::GuzzleHttp\Promise\{closure}()in TaskQueue.php line 47

**Comment by rolinger** [comment]
I am on PHP v7.3.11 and am getting this error too:

```
?details=true` resulted in a `404 Not Found` response:
{"error":"No information found about this instance id."}
 in /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/dev/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/dev\Promise::callHandler(1, Object(GuzzleH in /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

```
