### ISSUE TITLE
Call to undefined method GuzzleHttp\Handler\Proxy::wrapSync()

### ISSUE THREAD

**Issue by weogrim** [guzzle/guzzle#2337]
**Guzzle version(s) affected**: 6.3.3

**Description**  

I try to re-run code from about month ago, which use SlimPHP, and web-push-libs/web-push-php to send Push Notification. It all runs smooth, but now, this error occurs. 

`Call to undefined method GuzzleHttp\Handler\Proxy::wrapSync()`

I write here, because it looks like Guzzle problem, but I can't find any solution. When I try to search, it looks like no one ever gets this error. 

```
Slim Application Error
The application could not run because of the following error:

Details
Type: Error
Message: Call to undefined method GuzzleHttp\Handler\Proxy::wrapSync()
File: /mnt/e/firma/fbpopular/vendor/guzzlehttp/guzzle/src/functions.php
Line: 107
Trace
#0 /mnt/e/firma/fbpopular/vendor/guzzlehttp/guzzle/src/HandlerStack.php(40): GuzzleHttp\choose_handler()
#1 /mnt/e/firma/fbpopular/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /mnt/e/firma/fbpopular/vendor/minishlink/web-push/src/WebPush.php(101): GuzzleHttp\Client->__construct(Array)
#3 /mnt/e/firma/fbpopular/app/Controllers/NotificationsController.php(62): Minishlink\WebPush\WebPush->__construct(Array)
#4 [internal function]: App\Controllers\NotificationsController->sendNotification(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /mnt/e/firma/fbpopular/vendor/slim/slim/Slim/App.php(313): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /mnt/e/firma/fbpopular/public/index.php(36): Slim\App->run()
#14 {main}
```

**How to reproduce**  

```
use Minishlink\WebPush\Subscription as NotificationSubscription;
use Minishlink\WebPush\WebPush;

$subscriber = [
  'id' => 1,
  'endpoint' => 'https://fcm.googleapis.com/fcm/send/****',
  'publicKey' => '****',
  'authToken' => '****',
  'contentEncoding' => 'aes128gcm',
];

$subscription = NotificationSubscription::create($subscriber);

$auth = [
  'VAPID' => [
    'subject' => 'https://fbpopular.local/',
    'publicKey' => '****',
    'privateKey' => '****'
  ]
];

$webPush = new WebPush($auth);
\var_dump($webPush);
```
And there you can find WebPush class, which trigger Guzzle Client: https://github.com/web-push-libs/web-push-php/blob/master/src/WebPush.php

I run it on Windows 10, with Ubuntu WSL. My PHP is `PHP 7.2.19-0ubuntu0.18.04.1`

**Possible Solution**  

**Additional context**

**Comment by sagikazarmark** [comment]
Well, it is there: https://github.com/guzzle/guzzle/blob/6.3.3/src/Handler/Proxy.php#L21

Try deleting the vendor directory and run `composer install`again.

**Comment by weogrim** [comment]
It was weird, because I see 'missing' code in `vendor`. 

I close issue, deleting vendor and reinstall packages works :)
