### ISSUE TITLE
Guzzle 7 error message worse than Guzzle 6 error message for invalid proxy in StreamHandler

### ISSUE THREAD

**Issue by TimWolla** [guzzle/guzzle#2849]
**Guzzle version(s) affected**: Current git master (3a0543e4f589e21e8d65b984e544967c9de2b8b2 / 7.2.0)
**PHP version**: 7.4.12
**cURL version**: 7.64.0

**Description**  

The error message Guzzle 7 emits when the proxy is misconfigured with the StreamHandler is worse compared to the one in Guzzle 6. The type of the exception is better, though.

**How to reproduce**  

```php
<?php

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

require('vendor/autoload.php');

$client = new Client();

try {
	$request = new Request('GET', 'http://www.example.com');
	$response = $client->send($request, [
		'stream' => true,
	]);
	var_dump(substr($response->getBody(), 0, 100));
} catch (\Exception $e) {
	echo $e.PHP_EOL;
}
```

Guzzle 6:

```
root@d96cb194032e:/pwd/test# HTTP_PROXY=http://127.0.0.1:8888 php test2.php
RuntimeException: Error creating resource: [message] fopen(http://www.example.com): failed to open stream: Unable to find the socket transport "http" - did you forget to enable it when you configured PHP?
[file] /pwd/test/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /pwd/test/guzzlehttp/guzzle/src/Handler/StreamHandler.php:253
Stack trace:
#0 /pwd/test/guzzlehttp/guzzle/src/Handler/StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /pwd/test/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /pwd/test/guzzlehttp/guzzle/src/Handler/Proxy.php(52): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /pwd/test/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#4 /pwd/test/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#5 /pwd/test/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /pwd/test/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /pwd/test/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /pwd/test/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /pwd/test/guzzlehttp/guzzle/src/Client.php(112): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#10 /pwd/test/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#11 /pwd/test/test2.php(13): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#12 {main}

Next GuzzleHttp\Exception\RequestException: Error creating resource: [message] fopen(http://www.example.com): failed to open stream: Unable to find the socket transport "http" - did you forget to enable it when you configured PHP?
[file] /pwd/test/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /pwd/test/guzzlehttp/guzzle/src/Exception/RequestException.php:52
Stack trace:
#0 /pwd/test/guzzlehttp/guzzle/src/Handler/StreamHandler.php(68): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Psr7\Request), Object(RuntimeException))
#1 /pwd/test/guzzlehttp/guzzle/src/Handler/Proxy.php(52): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#2 /pwd/test/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#3 /pwd/test/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /pwd/test/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /pwd/test/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#6 /pwd/test/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /pwd/test/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /pwd/test/guzzlehttp/guzzle/src/Client.php(112): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#9 /pwd/test/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#10 /pwd/test/test2.php(13): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 {main}
```

Guzzle 7:

```
root@d96cb194032e:/pwd# HTTP_PROXY=http://127.0.0.1:8888 php test2.php
GuzzleHttp\Exception\ConnectException: Connection refused for URI http://www.example.com in /pwd/src/Handler/StreamHandler.php:311
Stack trace:
#0 /pwd/src/Handler/StreamHandler.php(230): GuzzleHttp\Handler\StreamHandler->GuzzleHttp\Handler\{closure}()
#1 /pwd/src/Handler/StreamHandler.php(322): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#2 /pwd/src/Handler/StreamHandler.php(58): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#3 /pwd/src/Handler/Proxy.php(48): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /pwd/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /pwd/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#6 /pwd/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /pwd/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /pwd/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#9 /pwd/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#10 /pwd/src/Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#11 /pwd/src/Client.php(123): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#12 /pwd/test2.php(13): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#13 {main}

Next GuzzleHttp\Exception\ConnectException: Connection refused for URI http://www.example.com in /pwd/src/Handler/StreamHandler.php:72
Stack trace:
#0 /pwd/src/Handler/Proxy.php(48): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#1 /pwd/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#2 /pwd/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /pwd/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#4 /pwd/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#5 /pwd/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /pwd/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /pwd/src/Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#8 /pwd/src/Client.php(123): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#9 /pwd/test2.php(13): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#10 {main}
```

**Possible Solution**  

The `ConnectException` should include the PHP errors in the message, like it did in Guzzle 6.

**Additional context**  

Somewhat related to #2848, as we experienced the issue with Guzzle 6 and I was confused by the differing (and less useful) error message in Guzzle 7 when filing the bug.

The Guzzle 6 message is slightly misleading, but at the very least it's Googleable, pointing to e.g. this issue: #1555

**Comment by Nyholm** [comment]
Could you submit a PR please?

**Comment by TimWolla** [comment]
I'll try to look into this, but it is just the error _message_ it is low-ish priority.
