### ISSUE TITLE
FileCookieJar fails on invalid UTF-8 characters

### ISSUE THREAD

**Issue by shaneiseminger** [guzzle/guzzle#2951]
**Guzzle version(s) affected**: 7.2.0
**PHP version**: 7.4.16
**cURL version**: 7.64.0

**Description**  
This is a weird one and not technically an issue with Guzzle. However, I'd expect Guzzle to handle it gracefully rather than throwing an exception since it's not anything that can be fixed in the implementation (other than replacing `FileCookieJar` with my own class).

**How to reproduce**  
From an instance in a Montréal datacenter (this is what triggers a cookie with malformed UTF-8 characters)
```
use GuzzleHttp\Client,
	GuzzleHttp\Cookie,
	GuzzleHttp\RequestOptions;

$client = new Client([
	RequestOptions::COOKIES => new Cookie\FileCookieJar(sys_get_temp_dir() . '/' . uniqid() . '.txt')
]);

$client->get('https://www.fastcompany.com/90688810/portillos-stock-ptlo-ipo-price?partner=rss&utm_content=rss');
```
Result:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\InvalidArgumentException: json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded in /var/www/vendor/guzzlehttp/guzzle/src/Utils.php:296
Stack trace:
#0 /var/www/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php(67): GuzzleHttp\Utils::jsonEncode(Array)
#1 /var/www/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php(47): GuzzleHttp\Cookie\FileCookieJar->save('/tmp/6171aa68c6...')
#2 [internal function]: GuzzleHttp\Cookie\FileCookieJar->__destruct()
#3 {main}
  thrown in /var/www/vendor/guzzlehttp/guzzle/src/Utils.php on line 296
  ```
You can see the malformed é in the headers here:
```
root:/var/www# curl -I "https://www.fastcompany.com/90688810/portillos-stock-ptlo-ipo-price?partner=rss&utm_content=rss"
HTTP/2 200 
server: nginx
content-type: text/html; charset=utf-8
x-dns-prefetch-control: off
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15552000; includeSubDomains
x-download-options: noopen
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
etag: W/"fe933-yPdihYBL59iyV5AoQEw8tstMh4I"
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
age: 284
set-cookie: X-abtest=a;
set-cookie: fastlygeo=Toronto:Canada:M6R:34.152.57.232; expires=Thu, 21 Oct 2021 18:04:05 GMT; path=/;
set-cookie: geodata=Toronto:Canada:M6R:34.152.57.232; expires=Fri, 22 Oct 2021 18:03:55 GMT; path=/;
last-modified: Thu, 21 Oct 2021 18:03:55 GMT
date: Thu, 21 Oct 2021 18:03:55 GMT
x-served-by: cache-bwi5170-BWI, cache-yyz4546-YYZ
x-cache: HIT, MISS
x-cache-hits: 1, 0
x-timer: S1634839436.718844,VS0,VE20
set-cookie: X-abtest=a;
set-cookie: fastlygeo=Montr�al:Canada:H3G:34.152.57.232; expires=Thu, 21 Oct 2021 18:04:05 GMT; path=/;
set-cookie: geodata=Montr�al:Canada:H3G:34.152.57.232; expires=Fri, 22 Oct 2021 18:03:55 GMT; path=/;
cache-control: max-age=0
vary: Accept-Encoding, Cookie, X-abtest
content-length: 1042739
```
**Possible Solution**  
- Use native `serialize()`
- Silently fail on invalid UTF-8 characters

This is specific enough that I'm not sure whether you want to fix it. I can certainly implement `CookieJarInterface` in my own class to work around the issue.

**Comment by zerkms** [comment]
Not stale.
