### ISSUE TITLE
[PHP 8.1] Deprecated: curl_multi_exec(): Passing null to parameter #2 ($still_running) of type int is deprecated

### ISSUE THREAD

**Issue by ruudk** [guzzle/guzzle#2990]
**Guzzle version(s) affected**: 7.4.1
**PHP version**: 8.1.3
**cURL version**: 7.81.0

**Description**  
After upgrading production from PHP 8.0 to PHP 8.1 I noticed the following deprecation:
```
Deprecated: curl_multi_exec(): Passing null to parameter #2 ($still_running) of type int is deprecated
```

**How to reproduce**  
```
ErrorException: Deprecated: curl_multi_exec(): Passing null to parameter #2 ($still_running) of type int is deprecated
#62 /vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(166): GuzzleHttp\Handler\CurlMultiHandler::tick
#61 /vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\Handler\CurlMultiHandler::execute
#60 /vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\Promise::invokeWaitFn
#59 /vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise::waitIfPending
#58 /vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise::invokeWaitList
#57 /vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise::waitIfPending
#56 /vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise::wait
#55 /vendor/php-http/guzzle7-adapter/src/Promise.php(94): Http\Adapter\Guzzle7\Promise::wait
#54 /vendor/php-http/guzzle7-adapter/src/Client.php(51): Http\Adapter\Guzzle7\Client::sendRequest
```

**Possible Solution**  

**Additional context**

**Comment by noriellecruz** [comment]
We got this error in the latest version of guzzle.

![image](https://user-images.githubusercontent.com/46517631/207975445-5b32506c-4272-4f1d-bc78-021732a2df8a.png)

Is it related?

**Comment by GrahamCampbell** [comment]
That error is not coming from the latest version. In the latest version, that function is not called on that line of the client.
