### ISSUE TITLE
force_ip_resolve v6 cuts http protocol from url

### ISSUE THREAD

**Issue by AndiLeni** [guzzle/guzzle#3021]
**Guzzle version(s) affected**: 7.4.3
**PHP version**: 7.4.19
**cURL version**: 7.70.0

**Description**  
If `force_ip_resolve` is set to `v6` the http protocol (http/https) seems to be cut off from the url.

**How to reproduce**  
```php
<?php

require 'vendor/autoload.php';

$client = new GuzzleHttp\Client(['base_uri' => "http://httpbin.org"]);

$client->request('GET', '/foo', ['force_ip_resolve' => 'v6']);
```

**Additional context**  
This throws the following error (note the missing http:// event though specified):
```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: httpbin.org (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://httpbin.org/foo in D:\Code\website-checker\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
Stack trace:
#0 D:\Code\website-checker\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\Code\website-checker\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\Code\website-checker\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\Code\website-checker\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php in D:\Code\website-checker\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 210
```

**Comment by TimWolla** [comment]
I don't see a bug here. The error message is about the host name not being resolvable (and it indeed doesn't have a AAAA record), there should not be a scheme there.

**Comment by AndiLeni** [comment]
Thanks for clarifying and sorry for the inconvenience. 
I was sure the http protocol should be there and given in the error message and did not think about a missing ipv6 connection.
